name: ramp-brainage
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas>=0.21
  - jupyter
  - matplotlib
  - scikit-learn>=0.19
  - seaborn
  - nilearn
  - pytorch
  - pip:
    - ramp-workflow
